-- Insert address data
INSERT OR IGNORE INTO address (street_address, city, post_code, subdivision_id, division_id, country_alpha2) VALUES
-- United States
('123 S Figueroa St', 'Los Angeles', '90001', 
 (SELECT id FROM subdivision WHERE name = 'Los Angeles County'),
 (SELECT id FROM division WHERE name = 'California'),
 'US'),
('1 World Trade Center', 'New York', '10007', 
 (SELECT id FROM subdivision WHERE name = 'New York County'),
 (SELECT id FROM division WHERE name = 'New York'),
 'US'),
('1100 Congress Ave', 'Austin', '78701', 
 (SELECT id FROM subdivision WHERE name = 'Travis County'),
 (SELECT id FROM division WHERE name = 'Texas'),
 'US'),
('400 S Orange Ave', 'Orlando', '32801', 
 (SELECT id FROM subdivision WHERE name = 'Orange County'),
 (SELECT id FROM division WHERE name = 'Florida'),
 'US'),
('233 S Wacker Dr', 'Chicago', '60606', 
 (SELECT id FROM subdivision WHERE name = 'Cook County'),
 (SELECT id FROM division WHERE name = 'Illinois'),
 'US'),

-- Canada
('100 Queen St W', 'Toronto', 'M5H 2N2', 
 (SELECT id FROM subdivision WHERE name = 'Toronto'),
 (SELECT id FROM division WHERE name = 'Ontario'),
 'CA'),
('275 Rue Notre-Dame E', 'Montreal', 'H2Y 1C6', 
 (SELECT id FROM subdivision WHERE name = 'Montreal'),
 (SELECT id FROM division WHERE name = 'Quebec'),
 'CA'),
('453 W 12th Ave', 'Vancouver', 'V5Y 1V4', 
 (SELECT id FROM subdivision WHERE name = 'Greater Vancouver'),
 (SELECT id FROM division WHERE name = 'British Columbia'),
 'CA'),
('1 Sir Winston Churchill Square', 'Edmonton', 'T5J 2R7', 
 (SELECT id FROM subdivision WHERE name = 'Edmonton'),
 (SELECT id FROM division WHERE name = 'Alberta'),
 'CA'),
('1841 Argyle St', 'Halifax', 'B3J 3A5', 
 (SELECT id FROM subdivision WHERE name = 'Halifax'),
 (SELECT id FROM division WHERE name = 'Nova Scotia'),
 'CA'),

-- France
('16 Rue de la Paix', 'Paris', '75002', 
 (SELECT id FROM subdivision WHERE name = 'Paris'),
 (SELECT id FROM division WHERE name = 'Île-de-France'),
 'FR'),
('2 Rue d''Arcole', 'Marseille', '13006', 
 (SELECT id FROM subdivision WHERE name = 'Marseille'),
 (SELECT id FROM division WHERE name = 'Provence-Alpes-Côte d''Azur'),
 'FR'),
('1 Place des Terreaux', 'Lyon', '69001', 
 (SELECT id FROM subdivision WHERE name = 'Lyon'),
 (SELECT id FROM division WHERE name = 'Auvergne-Rhône-Alpes'),
 'FR'),
('7 Rue du Palais de Justice', 'Bordeaux', '33000', 
 (SELECT id FROM subdivision WHERE name = 'Bordeaux'),
 (SELECT id FROM division WHERE name = 'Nouvelle-Aquitaine'),
 'FR'),
('1 Place du Capitole', 'Toulouse', '31000', 
 (SELECT id FROM subdivision WHERE name = 'Toulouse'),
 (SELECT id FROM division WHERE name = 'Occitanie'),
 'FR'),

-- United Kingdom
('10 Downing Street', 'London', 'SW1A 2AA', 
 (SELECT id FROM subdivision WHERE name = 'Greater London'),
 (SELECT id FROM division WHERE name = 'England'),
 'GB'),
('Victoria Square', 'Birmingham', 'B1 1BB', 
 (SELECT id FROM subdivision WHERE name = 'Birmingham'),
 (SELECT id FROM division WHERE name = 'England'),
 'GB'),
('City Hall, The Queen''s Walk', 'London', 'SE1 2AA', 
 (SELECT id FROM subdivision WHERE name = 'Greater London'),
 (SELECT id FROM division WHERE name = 'England'),
 'GB'),
('George Square', 'Glasgow', 'G2 1DU', 
 (SELECT id FROM subdivision WHERE name = 'Glasgow'),
 (SELECT id FROM division WHERE name = 'Scotland'),
 'GB'),
('City Chambers, High Street', 'Edinburgh', 'EH1 1YJ', 
 (SELECT id FROM subdivision WHERE name = 'Edinburgh'),
 (SELECT id FROM division WHERE name = 'Scotland'),
 'GB'),

-- India
('Mantralaya, Madam Cama Road', 'Mumbai', '400032', 
 (SELECT id FROM subdivision WHERE name = 'Mumbai'),
 (SELECT id FROM division WHERE name = 'Maharashtra'),
 'IN'),
('Delhi Secretariat, I.P. Estate', 'New Delhi', '110002', 
 (SELECT id FROM subdivision WHERE name = 'New Delhi'),
 (SELECT id FROM division WHERE name = 'Delhi'),
 'IN'),
('Fort St George', 'Chennai', '600009', 
 (SELECT id FROM subdivision WHERE name = 'Chennai'),
 (SELECT id FROM division WHERE name = 'Tamil Nadu'),
 'IN'),
('Vidhana Soudha', 'Bengaluru', '560001', 
 (SELECT id FROM subdivision WHERE name = 'Bengaluru Urban'),
 (SELECT id FROM division WHERE name = 'Karnataka'),
 'IN'),
('Writers'' Building, BBD Bagh', 'Kolkata', '700001', 
 (SELECT id FROM subdivision WHERE name = 'Kolkata'),
 (SELECT id FROM division WHERE name = 'West Bengal'),
 'IN'),

-- Bangladesh
('Bangladesh Secretariat', 'Dhaka', '1000', 
 (SELECT id FROM subdivision WHERE name = 'Dhaka City'),
 (SELECT id FROM division WHERE name = 'Dhaka'),
 'BD'),
('Chittagong City Corporation', 'Chittagong', '4000', 
 (SELECT id FROM subdivision WHERE name = 'Chittagong City'),
 (SELECT id FROM division WHERE name = 'Chittagong'),
 'BD'),
('Rajshahi City Corporation', 'Rajshahi', '6000', 
 (SELECT id FROM subdivision WHERE name = 'Rajshahi City'),
 (SELECT id FROM division WHERE name = 'Rajshahi'),
 'BD'),
('Khulna City Corporation', 'Khulna', '9100', 
 (SELECT id FROM subdivision WHERE name = 'Khulna City'),
 (SELECT id FROM division WHERE name = 'Khulna'),
 'BD'),
('Sylhet City Corporation', 'Sylhet', '3100', 
 (SELECT id FROM subdivision WHERE name = 'Sylhet City'),
 (SELECT id FROM division WHERE name = 'Sylhet'),
 'BD'),

-- Saudi Arabia
('Al Olaya Street', 'Riyadh', '12611', 
 (SELECT id FROM subdivision WHERE name = 'Riyadh'),
 (SELECT id FROM division WHERE name = 'Riyadh Region'),
 'SA'),
('Abraj Al Bait', 'Mecca', '24231', 
 (SELECT id FROM subdivision WHERE name = 'Mecca'),
 (SELECT id FROM division WHERE name = 'Makkah Region'),
 'SA'),
('King Fahd Road', 'Dammam', '32241', 
 (SELECT id FROM subdivision WHERE name = 'Dammam'),
 (SELECT id FROM division WHERE name = 'Eastern Province'),
 'SA'),
('Al Madinah Al Munawwarah Road', 'Medina', '42311', 
 (SELECT id FROM subdivision WHERE name = 'Medina'),
 (SELECT id FROM division WHERE name = 'Madinah Region'),
 'SA'),
('King Fahd Road', 'Khamis Mushait', '62411', 
 (SELECT id FROM subdivision WHERE name = 'Khamis Mushait'),
 (SELECT id FROM division WHERE name = 'Asir Region'),
 'SA'),

-- Japan
('2-8-1 Nishi-Shinjuku', 'Tokyo', '160-0023', 
 (SELECT id FROM subdivision WHERE name = 'Shinjuku'),
 (SELECT id FROM division WHERE name = 'Tokyo'),
 'JP'),
('1-1 Otemachi', 'Osaka', '540-8570', 
 (SELECT id FROM subdivision WHERE name = 'Osaka City'),
 (SELECT id FROM division WHERE name = 'Osaka'),
 'JP'),
('3-1-2 Sannomaru', 'Nagoya', '460-8501', 
 (SELECT id FROM subdivision WHERE name = 'Nagoya'),
 (SELECT id FROM division WHERE name = 'Aichi'),
 'JP'),
('Kita 3-jo Nishi 6-chome', 'Sapporo', '060-8588', 
 (SELECT id FROM subdivision WHERE name = 'Sapporo'),
 (SELECT id FROM division WHERE name = 'Hokkaido'),
 'JP'),
('1-7-85 Seavans North', 'Fukuoka', '812-8577', 
 (SELECT id FROM subdivision WHERE name = 'Fukuoka City'),
 (SELECT id FROM division WHERE name = 'Fukuoka'),
 'JP');